name: Deployment CI/CD

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
      
      - name: build the client
        run: cd client && npm install && npm run build

      - name: SSH config
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *
            StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: copy the frontend build to server
        run: "scp -v -r ./client/dist/* ${{ secrets.SSH_USERNAME }}@gdgsheridan.com:/home/${{ secrets.SSH_USERNAME }}/public_html/"
      
      - name: copy the backend to server
        run: "scp -v -r ./server/* ${{ secrets.SSH_USERNAME }}@gdgsheridan.com:/home/${{ secrets.SSH_USERNAME }}/www/backend"
        
      - name: backend config
        run: |
          ssh -v ${{ secrets.SSH_USERNAME }}@gdgsheridan.com << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
          nvm install stable
          cd /home/${{ secrets.SSH_USERNAME }}/www/backend
          npm install
          pm2 restart backend
          EOF